import { LitElement, html, css, type TemplateResult } from 'lit'
import { customElement, state } from 'lit/decorators.js'
import { repeat } from 'lit/directives/repeat.js'

import { routePath } from '../app/paths.js'
import { loadElements, summarise, type ElementDoc } from '../data/cem.js'
import { siteControlStyles, siteProseStyles, siteStyles } from '../styles/shared.js'

/**
 * The catalogue.
 *
 * Built from `custom-elements.json`, which the elements build emits from the source - so this page
 * lists what the package actually registers rather than what someone remembered to write down. An
 * element added to `@openish/elements` appears here; one that is removed disappears.
 */
@customElement('site-page-elements')
export class SitePageElements extends LitElement {
  static override styles = [
    siteStyles,
    siteControlStyles,
    siteProseStyles,
    css`
      :host {
        display: block;
      }

      input[type='search'] {
        inline-size: min(100%, 24rem);
        font: var(--openish-font-body);
        color: var(--openish-color-text);
        background: var(--openish-color-surface-raised);
        border: var(--openish-border-control-width) solid var(--openish-border-control-color);
        border-radius: var(--openish-radius-md);
        padding: var(--openish-space-2xs) var(--openish-space-sm);
        margin-bottom: var(--openish-space-md);
      }

      ul {
        display: grid;
        gap: var(--openish-space-sm);
        grid-template-columns: repeat(auto-fill, minmax(20rem, 1fr));
        padding: 0;
        margin: 0;
        list-style: none;
        max-width: none;
      }

      li {
        margin: 0;
      }

      a.card {
        display: block;
        block-size: 100%;
        padding: var(--openish-space-sm);
        color: var(--openish-color-text);
        background: var(--openish-color-surface);
        border: 1px solid var(--openish-color-border);
        border-radius: var(--openish-radius-lg);
      }

      a.card:hover {
        text-decoration: none;
        background: var(--openish-color-surface-hover);
      }

      .tag {
        font: var(--openish-font-code);
        color: var(--openish-color-link);
      }

      .summary {
        margin: var(--openish-space-3xs) 0 var(--openish-space-2xs);
        font: var(--openish-font-small);
        color: var(--openish-color-text-muted);
        max-width: none;
      }

      .counts {
        font: var(--openish-font-micro);
        color: var(--openish-color-text-muted);
      }

      .status {
        font: var(--openish-font-small);
        color: var(--openish-color-text-muted);
      }
    `,
  ]

  @state()
  private elements: readonly ElementDoc[] = []

  @state()
  private failed = false

  @state()
  private filter = ''

  override async connectedCallback(): Promise<void> {
    super.connectedCallback()
    try {
      this.elements = await loadElements()
    } catch {
      this.failed = true
    }
  }

  get #shown(): readonly ElementDoc[] {
    const needle = this.filter.trim().toLowerCase()
    if (needle === '') {
      return this.elements
    }
    return this.elements.filter(
      (element) =>
        element.tag.includes(needle) || element.description.toLowerCase().includes(needle),
    )
  }

  override render(): TemplateResult {
    const shown = this.#shown

    return html`
      <h1>Every element</h1>
      <p class="lede">
        ${this.elements.length > 0 ? `${this.elements.length} custom elements` : 'The custom elements'},
        read from the manifest the build emits — so this page lists what the package registers, not
        what someone remembered to write down. Most of them are usable on their own, without a
        reference around them.
      </p>

      <input
        type="search"
        aria-label="Filter elements"
        placeholder="Filter by name or description"
        .value=${this.filter}
        @input=${(event: Event) => {
          this.filter = (event.target as HTMLInputElement).value
        }}
      />

      ${this.failed
        ? html`<p class="status">
            The manifest could not be loaded. It is generated by
            <code>npm run build -w @openish/elements</code>.
          </p>`
        : this.elements.length === 0
          ? html`<p class="status">Loading the manifest…</p>`
          : html`
              <p class="status">
                ${shown.length === this.elements.length
                  ? ''
                  : `${shown.length} of ${this.elements.length}`}
              </p>
              <ul>
                ${repeat(
                  shown,
                  (element) => element.tag,
                  (element) => html`
                    <li>
                      <a class="card" href=${routePath(`elements/${element.tag}`)}>
                        <span class="tag">&lt;${element.tag}&gt;</span>
                        <p class="summary">${summarise(element.description)}</p>
                        <span class="counts">
                          ${element.properties.length}
                          ${element.properties.length === 1 ? 'property' : 'properties'}${element.events
                            .length > 0
                            ? ` · ${element.events.length} ${element.events.length === 1 ? 'event' : 'events'}`
                            : ''}
                        </span>
                      </a>
                    </li>
                  `,
                )}
              </ul>
            `}
    `
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'site-page-elements': SitePageElements
  }
}
