import { LitElement, html, css, type TemplateResult } from 'lit'
import { customElement, property, state } from 'lit/decorators.js'
import { repeat } from 'lit/directives/repeat.js'

import '../components/site-example.js'
import { routePath } from '../app/paths.js'
import { loadElements, type ElementDoc } from '../data/cem.js'
import { STANDALONE_EXAMPLES } from '../data/standalone.js'
import { siteProseStyles, siteStyles } from '../styles/shared.js'

/**
 * One element's page.
 *
 * The tables come from the manifest, and the live instance - where there is one - comes from
 * `standalone.ts`, which is a `SiteExampleSpec` like every other example on the site and is checked
 * against the same manifest by `apps/site/test/examples.test.ts`. An element documented here with a
 * demo that had drifted from its API would fail the build in Node.
 *
 * Not every element gets one. `<openish-operation>` needs a document store through context and
 * `<openish-try-it>` needs a request; standing either of them up on their own would mean building
 * most of a reference to do it, and the page says so rather than pretending the list is complete.
 */
@customElement('site-page-element')
export class SitePageElement extends LitElement {
  static override styles = [
    siteStyles,
    siteProseStyles,
    css`
      :host {
        display: block;
      }

      .tag {
        font: var(--openish-font-code);
      }

      .scroller {
        overflow-x: auto;
        margin-bottom: var(--openish-space-md);
      }

      table {
        border-collapse: collapse;
        inline-size: 100%;
        min-inline-size: 34rem;
        font: var(--openish-font-small);
      }

      th,
      td {
        text-align: start;
        vertical-align: top;
        padding: var(--openish-space-2xs) var(--openish-space-sm);
        border-bottom: 1px solid var(--openish-color-border);
      }

      thead th {
        font: var(--openish-font-small-bold);
        color: var(--openish-color-text-muted);
      }

      code {
        font: var(--openish-font-code-small);
        overflow-wrap: anywhere;
      }

      .description {
        white-space: pre-wrap;
        max-width: 68ch;
      }

      .status {
        font: var(--openish-font-small);
        color: var(--openish-color-text-muted);
      }
    `,
  ]

  /** The tag from the URL. Set by the route, which is where the parameter arrives. */
  @property({ type: String })
  tag = ''

  @state()
  private elements: readonly ElementDoc[] = []

  @state()
  private failed = false

  override async connectedCallback(): Promise<void> {
    super.connectedCallback()
    try {
      this.elements = await loadElements()
    } catch {
      this.failed = true
    }
  }

  get #element(): ElementDoc | undefined {
    return this.elements.find((element) => element.tag === this.tag)
  }

  #properties(element: ElementDoc): TemplateResult {
    return html`
      <h2>Properties</h2>
      <div class="scroller">
        <table>
          <thead>
            <tr>
              <th scope="col">Property</th>
              <th scope="col">Attribute</th>
              <th scope="col">Type</th>
              <th scope="col">Default</th>
              <th scope="col">What it does</th>
            </tr>
          </thead>
          <tbody>
            ${repeat(
              element.properties,
              (member) => member.name,
              (member) => html`
                <tr>
                  <td><code>${member.name}</code></td>
                  <td>${member.attribute ? html`<code>${member.attribute}</code>` : '—'}</td>
                  <td><code>${member.type || '—'}</code></td>
                  <td>${member.default ? html`<code>${member.default}</code>` : '—'}</td>
                  <td>${member.description}</td>
                </tr>
              `,
            )}
          </tbody>
        </table>
      </div>
    `
  }

  override render(): TemplateResult {
    if (this.failed) {
      return html`
        <h1>Not available</h1>
        <p class="status">
          The manifest could not be loaded. It is generated by
          <code>npm run build -w @openish/elements</code>.
        </p>
      `
    }

    if (this.elements.length === 0) {
      return html`<p class="status">Loading…</p>`
    }

    const element = this.#element
    if (!element) {
      return html`
        <h1>No such element</h1>
        <p class="lede">
          Nothing in the manifest is called <code>${this.tag}</code>.
          <a href=${routePath('elements')}>Back to the catalogue</a>.
        </p>
      `
    }

    const example = STANDALONE_EXAMPLES[element.tag]

    return html`
      <p class="status"><a href=${routePath('elements')}>← Every element</a></p>
      <h1 class="tag">&lt;${element.tag}&gt;</h1>
      <p class="description">${element.description}</p>

      ${example
        ? html`
            <h2>On its own</h2>
            <p>
              No reference around it, no document store — this is the element by itself, and the
              listing is the markup that produced it.
            </p>
            <site-example .example=${example}></site-example>
          `
        : ''}

      ${element.properties.length > 0 ? this.#properties(element) : ''}

      ${element.events.length > 0
        ? html`
            <h2>Events</h2>
            <div class="scroller">
              <table>
                <thead>
                  <tr>
                    <th scope="col">Event</th>
                    <th scope="col">When</th>
                  </tr>
                </thead>
                <tbody>
                  ${repeat(
                    element.events,
                    (event) => event.name,
                    (event) => html`
                      <tr>
                        <td><code>${event.name}</code></td>
                        <td>${event.description}</td>
                      </tr>
                    `,
                  )}
                </tbody>
              </table>
            </div>
          `
        : ''}
    `
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'site-page-element': SitePageElement
  }
}
