import manifestUrl from '../../../../packages/elements/custom-elements.json?url'

/**
 * The element catalogue, read from the manifest the elements build emits.
 *
 * `custom-elements.json` is generated by `cem analyze` and gitignored, so it is not a file this site
 * can import as a module and typecheck against - it does not exist in a fresh clone. It is fetched
 * at runtime instead, which has the added virtue of keeping four hundred kilobytes of JSON out of
 * every page that is not the catalogue.
 *
 * What the manifest actually carries is narrower than the plan for this page assumed: descriptions,
 * attributes, public fields and events. There are no `cssParts` or `slots` entries in it, because
 * nothing annotates them for the analyzer - so the catalogue does not claim to list them. A page
 * that showed an empty "Parts" heading for all thirty-one elements would be describing the
 * analyzer's configuration rather than the components.
 */
export type ElementMember = {
  readonly name: string
  readonly type: string
  readonly default: string
  readonly description: string
  /** The attribute form, when the property has one. */
  readonly attribute: string
}

export type ElementEvent = {
  readonly name: string
  readonly description: string
}

export type ElementDoc = {
  readonly tag: string
  readonly description: string
  readonly properties: readonly ElementMember[]
  readonly events: readonly ElementEvent[]
}

type RawAttribute = { name?: string; fieldName?: string }
type RawMember = {
  kind?: string
  name?: string
  privacy?: string
  static?: boolean
  type?: { text?: string }
  default?: string
  description?: string
}
type RawDeclaration = {
  tagName?: string
  description?: string
  attributes?: RawAttribute[]
  members?: RawMember[]
  events?: { name?: string; description?: string }[]
}

/** The first line of a description, for a list that has one row per element. */
export const summarise = (description: string): string =>
  description.split('\n').find((line) => line.trim() !== '')?.trim() ?? ''

const normalise = (declaration: RawDeclaration): ElementDoc => {
  const attributeFor = new Map(
    (declaration.attributes ?? [])
      .filter((attribute) => attribute.fieldName && attribute.name)
      .map((attribute) => [attribute.fieldName!, attribute.name!]),
  )

  return {
    tag: declaration.tagName ?? '',
    description: declaration.description ?? '',
    properties: (declaration.members ?? [])
      .filter((member) => member.kind === 'field' && member.privacy !== 'private' && !member.static)
      .map((member) => ({
        name: member.name ?? '',
        type: member.type?.text ?? '',
        default: member.default ?? '',
        description: member.description ?? '',
        attribute: attributeFor.get(member.name ?? '') ?? '',
      })),
    events: (declaration.events ?? []).map((event) => ({
      name: event.name ?? '',
      description: event.description ?? '',
    })),
  }
}

/**
 * Every element in the manifest, in tag order.
 *
 * Fetched once and remembered. The catalogue index and each detail page ask for it independently,
 * and a reader clicking through five elements should not fetch four hundred kilobytes five times.
 */
let pending: Promise<readonly ElementDoc[]> | undefined

export const loadElements = async (): Promise<readonly ElementDoc[]> => {
  pending ??= (async () => {
    const response = await fetch(manifestUrl)
    if (!response.ok) {
      throw new Error(`custom-elements.json: ${response.status}`)
    }
    const manifest = (await response.json()) as { modules?: { declarations?: RawDeclaration[] }[] }
    return (manifest.modules ?? [])
      .flatMap((module) => module.declarations ?? [])
      .filter((declaration) => declaration.tagName)
      .map(normalise)
      .sort((left, right) => left.tag.localeCompare(right.tag))
  })()
  return pending
}
