import type { OperationObject } from '@scalar/openapi-types/3.1'

import { findSnippetClient, type SnippetClient } from './snippet.js'

/**
 * A code sample the document's author wrote, rather than one openish generated.
 *
 * The generated snippet describes the HTTP request. An author-supplied one usually describes
 * something better - the SDK call a reader would actually write - and no amount of HAR gets there.
 * Where a document offers one, it wins for that language.
 */
export type AuthorSample = {
  /** Picker id, namespaced so it can never collide with a `target/client` from snippetz. */
  id: string
  /** What the picker shows, e.g. `Node.js SDK`. */
  label: string
  /** Group heading in the picker, from the declared language. */
  targetLabel: string
  /** highlight.js language, borrowed from the matching snippetz target where one exists. */
  language: string
  source: string
}

/**
 * The extensions that carry author samples, most trusted first.
 *
 * Seven spellings exist because seven tools invented this independently, and a document generated by
 * a toolchain often carries more than one - Stainless emits its own alongside whatever the author
 * wrote by hand. Reading them all and concatenating would show the same request three times, so the
 * **first list that has anything in it wins** and the rest are ignored. That is Scalar's rule too,
 * and the order matters: `x-codeSamples` is the OpenAPI-community spelling an author writes on
 * purpose, so it outranks anything a generator added.
 */
const SOURCES = [
  'x-codeSamples',
  'x-code-samples',
  'x-custom-examples',
  'x-scalar-examples',
  'x-stainless-snippets',
  'x-stainless-examples',
  'x-readme',
] as const

/**
 * Extensions whose samples live one key further down.
 *
 * `x-readme` is a namespace rather than a list - the samples are at `x-readme.code-samples`, and
 * everything else under that key is ReadMe's own configuration. Reading the namespace itself treated
 * `code-samples` as a language name and found no source, so a ReadMe-generated document showed
 * nothing at all.
 */
const NESTED_UNDER: Readonly<Record<string, string>> = {
  'x-readme': 'code-samples',
}

/** Per-language display names, for a language snippetz has no target for. */
const LANGUAGE_LABELS: Record<string, string> = {
  bash: 'Shell',
  csharp: 'C#',
  curl: 'Shell',
  golang: 'Go',
  javascript: 'JavaScript',
  js: 'JavaScript',
  node: 'Node.js',
  objectivec: 'Objective-C',
  php: 'PHP',
  python: 'Python',
  ruby: 'Ruby',
  shell: 'Shell',
  typescript: 'TypeScript',
  ts: 'TypeScript',
}

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value)

/**
 * How a language name maps to a highlight language and a group heading.
 *
 * A declared language is matched against snippetz's own targets first, so `python` gets the same
 * heading as the generated Python clients and the two sit together in the picker instead of in two
 * groups spelled the same way.
 */
const describeLanguage = (language: string): { language: string; targetLabel: string } => {
  const normalised = language.trim().toLowerCase()
  const target: SnippetClient | undefined = findSnippetClient(`${normalised}/fetch`) ?? undefined

  return {
    language: target?.language ?? normalised ?? 'plaintext',
    targetLabel: target?.targetLabel ?? LANGUAGE_LABELS[normalised] ?? (language.trim() || 'Examples'),
  }
}

/**
 * Reads one entry, whichever of the four shapes it is in.
 *
 * `x-codeSamples` and friends use `{ lang, label?, source }`. `x-scalar-examples` uses
 * `{ lang, label?, source }` too. `x-stainless-snippets` and `x-readme` nest differently, so the
 * value is probed for the keys rather than narrowed to one shape - the alternative is four readers
 * that are 90% the same.
 */
const readEntry = (value: unknown, index: number): AuthorSample | undefined => {
  if (!isRecord(value)) {
    return undefined
  }

  const source = value['source'] ?? value['code'] ?? value['snippet']
  if (typeof source !== 'string' || source.trim() === '') {
    return undefined
  }

  const declared = value['lang'] ?? value['language']
  const languageName = typeof declared === 'string' ? declared : 'plaintext'
  const { language, targetLabel } = describeLanguage(languageName)

  const label = value['label'] ?? value['name'] ?? value['title']

  return {
    id: `author/${index}/${languageName}`,
    label: typeof label === 'string' && label.trim() !== '' ? label.trim() : targetLabel,
    targetLabel,
    language,
    source,
  }
}

/**
 * The samples an operation's author supplied, or an empty list.
 *
 * A map-shaped extension (`{ python: {...}, node: {...} }`, which is how `x-stainless-snippets` and
 * `x-readme` are written) is read as its entries, with the key standing in for a missing `lang`.
 */
export const authorSamples = (operation: OperationObject | undefined): AuthorSample[] => {
  if (!operation) {
    return []
  }

  const record = operation as unknown as Record<string, unknown>

  for (const key of SOURCES) {
    const nested = NESTED_UNDER[key]
    const outer = record[key]
    const declared = nested === undefined ? outer : isRecord(outer) ? outer[nested] : undefined

    if (Array.isArray(declared)) {
      const samples = declared.map((entry, index) => readEntry(entry, index)).filter((s): s is AuthorSample => Boolean(s))
      if (samples.length > 0) {
        return samples
      }
      continue
    }

    if (isRecord(declared)) {
      const samples = Object.entries(declared)
        .map(([language, entry], index) =>
          readEntry(isRecord(entry) && entry['lang'] === undefined ? { lang: language, ...entry } : entry, index),
        )
        .filter((s): s is AuthorSample => Boolean(s))
      if (samples.length > 0) {
        return samples
      }
    }
  }

  return []
}
