import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

import { ALL_EXAMPLES } from '../src/data/examples.js'
import { attributesOf, printExample, rootTagOf } from '../src/data/example.js'

/*
 * The check that stands in for `lit-analyzer`.
 *
 * Every other template in this repository is verified by the analyzer, which reads the elements'
 * own declarations and fails the build for a binding that does not exist. A `<site-example>` is a
 * *string*, so the analyzer cannot see it - which is the price of the code listing and the running
 * demo being the same artefact. This is what is bought with that price: the same question, asked of
 * the same source of truth, in Node, in milliseconds.
 *
 * `custom-elements.json` is generated by the elements build and gitignored, so it is absent in a
 * fresh clone. Failing with the command to run beats skipping: a check that quietly does nothing is
 * worse than one that is briefly inconvenient.
 */

const MANIFEST = fileURLToPath(new URL('../../../packages/elements/custom-elements.json', import.meta.url))

type CemAttribute = { name?: string }
type CemMember = { kind?: string; name?: string; privacy?: string; static?: boolean }
type CemDeclaration = {
  tagName?: string
  attributes?: CemAttribute[]
  members?: CemMember[]
}
type Manifest = { modules?: { declarations?: CemDeclaration[] }[] }

const readManifest = (): Manifest => {
  if (!existsSync(MANIFEST)) {
    throw new Error(
      `custom-elements.json is missing. Run \`npm run build -w @openish/elements\` and try again.`,
    )
  }
  return JSON.parse(readFileSync(MANIFEST, 'utf8')) as Manifest
}

const declarations = new Map<string, CemDeclaration>()
for (const module of readManifest().modules ?? []) {
  for (const declaration of module.declarations ?? []) {
    if (declaration.tagName) {
      declarations.set(declaration.tagName, declaration)
    }
  }
}

/** Attributes the element declares, plus the global ones any element may carry. */
const attributesFor = (declaration: CemDeclaration): Set<string> =>
  new Set([
    ...(declaration.attributes ?? []).map((attribute) => attribute.name ?? ''),
    'class',
    'id',
    'style',
    'slot',
    'part',
    'hidden',
  ])

/** Public instance fields, which is what a host is allowed to assign. */
const propertiesFor = (declaration: CemDeclaration): Set<string> =>
  new Set(
    (declaration.members ?? [])
      .filter((member) => member.kind === 'field' && member.privacy !== 'private' && !member.static)
      .map((member) => member.name ?? ''),
  )

describe('the manifest is available', () => {
  it('declares the elements the examples use', () => {
    expect(declarations.size).toBeGreaterThan(20)
    expect(declarations.has('openish-api-reference')).toBe(true)
  })
})

describe.each(Object.entries(ALL_EXAMPLES))('%s', (name, example) => {
  const tag = rootTagOf(example.markup)

  it('starts with an element the manifest declares', () => {
    expect(tag, `${name} has no root tag`).toBeDefined()
    expect(declarations.has(tag!), `${name} uses <${tag}>, which no element declares`).toBe(true)
  })

  it('writes only attributes that element takes', () => {
    const declared = attributesFor(declarations.get(tag!)!)
    for (const attribute of attributesOf(example.markup)) {
      expect(declared.has(attribute), `${name}: <${tag}> has no "${attribute}" attribute`).toBe(true)
    }
  })

  it('sets only properties that element has', () => {
    const declared = propertiesFor(declarations.get(tag!)!)
    for (const key of Object.keys(example.props ?? {})) {
      expect(declared.has(key), `${name}: <${tag}> has no "${key}" property`).toBe(true)
    }
  })

  /*
   * The listing is what a reader copies, so it has to be complete. An example with property-only
   * configuration whose listing shows a bare tag would be showing the half that does nothing.
   */
  it('prints a listing that includes its property-only configuration', () => {
    const listing = printExample(example)
    expect(listing).toContain(example.markup)
    for (const key of Object.keys(example.props ?? {})) {
      expect(listing, `${name}: the listing never mentions ${key}`).toContain(`reference.${key}`)
    }
  })
})
